# rbac: sa - react2shell
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: react2shell
  namespace: insecure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: react2shell
  namespace: insecure
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "watch", "create"]   # create on pods/exec = the exec capability
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: react2shell
  namespace: insecure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: react2shell
subjects:
  - kind: ServiceAccount
    name: react2shell
    namespace: insecure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: react2shell
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets","namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: react2shell
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: react2shell
subjects:
  - kind: ServiceAccount
    name: react2shell
    namespace: insecure
