apiVersion: v1
kind: Service
metadata:
  name: react2shell
  namespace: secure-frontend
  labels:
    app: react2shell
spec:
  selector:
    app: react2shell
  ports:
    - name: http
      port: 3000
      targetPort: 3000
